src/app/pages/test-page/test-page.component.ts
=> FIx linting issue

package.json, yarn.lock
=> Update applicationinsights version in package.json

charts/opal-frontend/values.stg.template.yaml
=> Add OPAL_API_URL environment variable

server/sso/sso-authenticated.ts
=> Remove redundant code for token check

cypress/e2e/smoke/PO-151_signOutTest.feature, cypress/support/step_definitions/signInPage/signOutTest.ts
https://tools.hmcts.net/jira/browse/PO-151
Automated tests for PO-151
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] tests have been updated / new tests has been added (if needed)
=> automated tests for PO-151

charts/opal-frontend/values.stg.template.yaml
=> Update OPAL frontend values.stg.template.yaml

charts/opal-frontend/values.stg.template.yaml
Reverts hmcts/opal-frontend#134
=> Revert "Update OPAL frontend values.stg.template.yaml"

cypress/support/step_definitions/signInPage/signInTest.ts
=> adding long wait

cypress/support/step_definitions/signInPage/signInTest.ts
Reverts hmcts/opal-frontend#136
=> Revert "adding long wait"

server/routes.ts, server/sso/sso-authenticated.ts, server/sso/sso-login-callback.ts, server/sso/sso-login.ts, server/sso/sso-logout-callback.ts, server/sso/sso-logout.ts, server/stubs/sso/sso-authenticated.stub.ts, server/stubs/sso/sso-login-callback.stub.ts, server/stubs/sso/sso-login.stub.ts, server/stubs/sso/sso-logout-callback.stub.ts
=> Added logging

server/sso/sso-login-callback.ts
=> Add logging of request body in sso-login-callback.ts

charts/opal-frontend/values.stg.template.yaml
=> Add opal fines service instance for stging pod

cypress/support/step_definitions/signInPage/signInTest.ts
=> add waits on tests

charts/opal-frontend/values.stg.template.yaml
=> Update ingress host name

charts/opal-frontend/values.stg.template.yaml
Reverts hmcts/opal-frontend#143
=> Revert "Update ingress host name"

server/routes.ts, server/sso/sso-login.ts
=> Refactor SSO login route to handle errors and redirects

cypress/support/step_definitions/signInPage/signInTest.ts
Reverts hmcts/opal-frontend#142
=> Revert "add waits on tests"

server/sso/sso-authenticated.ts, server/sso/sso-login-callback.ts, server/sso/sso-login.ts, server/sso/sso-logout-callback.ts, server/sso/sso-logout.ts, server/stubs/sso/sso-authenticated.stub.ts, server/stubs/sso/sso-login-callback.stub.ts, server/stubs/sso/sso-login.stub.ts, server/stubs/sso/sso-logout-callback.stub.ts
=> Removed additional logging

server/sso/sso-logout.ts
=> Fix error handling in sso-logout module

config/default.json, config/dev.json, server/session/session-storage.ts
Reverts hmcts/opal-frontend#159
=> Revert "Enable redis"

server/sso/sso-login-callback.ts
Reverts hmcts/opal-frontend#164
=> Revert "Added 504 logging"

server/sso/sso-login-callback.ts
=> Added 504 logging

server/routes.ts, server/sso/sso-login-callback.ts
=> Test change to way logincallback called

server/routes.ts, server/routes_2.ts, server/sso/sso-login-callback.ts
Reverts hmcts/opal-frontend#177
=> Revert "Test change to way logincallback called"

server/routes_2.ts, server/sso/sso-authenticated.ts
Reverts hmcts/opal-frontend#183
=> Revert "Staging sso test"

server/sso/sso-authenticated.ts
=> Add logging for user authentication

server/session/session-storage.ts
=> Add Redis connection and ping logging

server/session/session-storage.ts
Reverts hmcts/opal-frontend#188
=> Revert "Add Redis connection and ping logging"

server/session/session-storage.ts
=> Add Redis connection and ping logging to SessionStorage

server/session/session-storage.ts
=> Refactor Redis ping in SessionStorage class

server/sso/sso-login-callback.ts, server/sso/sso-login.ts
=> Add logging statements to sso-login-callback.ts and sso-login.ts

server/sso/sso-login-callback.ts, server/sso/sso-login.ts
Reverts hmcts/opal-frontend#194
=> Revert "Add logging statements to sso-login-callback.ts and sso-login.ts"

server/session/session-storage.ts
=> Commented out Redis ping code

server.ts, server/session/session-storage.ts
=> More logging two

server.ts
Reverts hmcts/opal-frontend#201
=> Revert "More logging two"

angular.json, charts/opal-frontend/values.yaml, server.ts, server/sso/sso-login.ts, server/sso/sso-logout.ts, src/main.ts
Reverts hmcts/opal-frontend#208
=> Revert "Error message"

angular.json
=> Add external dependencies to angular.json

angular.json
Reverts hmcts/opal-frontend#210
=> Revert "Add external dependencies to angular.json"

server/session/session-storage.ts
=> Add Redis connection event listeners

server/session/session-storage.ts
=> Log redis error

server.ts, server/modules/health/index.ts, server/modules/index.ts, server/session/session-storage.ts
=> Added redis healthcheck

cypress/support/step_definitions/signInPage/signInTest.ts, server/sso/sso-logout.ts
=> Logout redirect

server/session/session-storage.ts
=> Remove redundant Redis event listeners

server.ts
=> Refactor server.ts to remove unnecessary code

server/stubs/sso/sso-login-callback.stub.ts
=> Update SSO login callback stub to use GET request for token retrieval

server/modules/helmet/index.ts
=> Add Dynatrace domain to connectSrc directive in Helmet module

README.md
=> Update accessibility test command in README

cypress/e2e/functional/PO-115_accountSearch.feature, cypress/e2e/functional/PO-116_accountMatches.feature, cypress/e2e/functional/PO-117_accountDetails.feature, cypress/e2e/smoke/PO-224_accessibilityTests.feature, cypress/support/step_definitions/accessibility/accessibility.ts
https://tools.hmcts.net/jira/browse/PO-224
=> Adding Accessibility tests to smoke test

.vscode/extensions.json, .vscode/settings.json
=> Vscode setup

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/components/govuk-header/govuk-header.component.ts, src/app/pages/account-enquiry/search/search.component.ts, src/app/services/auth-service/auth.service.spec.ts, src/app/services/auth-service/auth.service.ts, src/app/services/court-service/court.service.spec.ts, src/app/services/court-service/court.service.ts, src/app/services/defendant-account-service/defendant-account.service.ts, src/app/services/state-service/state.service.spec.ts, src/app/services/state-service/state.service.ts, tsconfig.json
=> Cache courts

server/interfaces/securityToken.ts, server/interfaces/userState.ts
=> Update SecurityToken interface

cypress/support/step_definitions/modeSwitch/modeSwitch.ts
=> condition for staging.staging

src/app/interfaces/add-defendant-account-note-body.ts, src/app/interfaces/defendant-account-details.interface.ts, src/app/mocks/add-defendant-account-note.mock.ts, src/app/mocks/defendant-account-details.mock.ts, src/app/pages/account-enquiry/details/details.component.spec.ts, src/app/pages/account-enquiry/details/details.component.ts
https://tools.hmcts.net/jira/browse/PO-239
=> Add businessUnitId to defendant account interfaces and mocks

src/app/services/launch-darkly/launch-darkly.service.spec.ts
=> Refactor LaunchDarklyService test suite

charts/opal-frontend/Chart.yaml, charts/opal-frontend/values.dev.template.yaml, charts/opal-frontend/values.stg.template.yaml, charts/opal-frontend/values.yaml
=> Disable Launch Darkly feature flag in dev and stg environments

src/app/pages/account-enquiry/search/search.component.html
=> Remove test flag from search component HTML

server/stubs/sso/sso-login-callback.stub.ts
=> PO-242: Use updated response from backend

charts/opal-frontend/values.stg.template.yaml
=> Add SSO feature to frontend

charts/opal-frontend/values.yaml
=> Add SSO feature to Opal frontend

charts/opal-frontend/Chart.yaml
=> Update opal-frontend version to 0.0.53

cypress/support/step_definitions/signInPage/signInTest.ts, src/app/services/auth-service/auth.service.spec.ts, src/app/services/auth-service/auth.service.ts
=> Fix authentication error handling in AuthService

config/default.json, package.json, yarn.lock
=> Remove max age to align with DARTS

config/default.json, package.json, yarn.lock
Reverts hmcts/opal-frontend#384
=> Revert "Remove max age to align with DARTS"

package.json, yarn.lock
=> Update tar dependency to version 6.2.1

config/default.json, server/sso/sso-authenticated.ts, server/stubs/sso/sso-authenticated.stub.ts, server/utils/base64.ts, server/utils/index.ts, server/utils/jwt.ts
=> Jwt token exp

server/api/proxy.ts
=> Switch back to use target as seems to be working now

package.json
=> Update dependency superagent to v9

package.json, yarn.lock
=> Remove tar resolution

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PO-454
=> remove @types/helmet dependency as deprecated

server/csrf-token/csrf-token.ts
=> refactor: Update CSRFToken ignore list

cypress/e2e/smoke/opal/PO-224_accessibilityTests.feature, cypress/support/step_definitions/accessibility/accessibility.ts, yarn.lock
=> add manual account creation scenarios to accessibility tests

src/app/app-routing.module.ts, src/app/enums/routing-paths.ts, src/app/pages/manual-account-creation/create-account/create-account.component.html, src/app/pages/manual-account-creation/offence-details/offence-details.component.html, src/app/pages/manual-account-creation/offence-details/offence-details.component.spec.ts, src/app/pages/manual-account-creation/offence-details/offence-details.component.ts
N/A
- Remove the merging tag issues on the create-account component
- Add offence details boiler plate component in readiness for future tickets
=> Add manual account creation offence details route and component, remove merging tag issue on create-account component

server/csrf-token/csrf-token.ts, server/session/session-storage.ts
=> Change cookies from lax to strict

cypress/e2e/functional/opal/manualAccountCreation/PO-280_employerDetails.feature, cypress/e2e/functional/opal/manualAccountCreation/PO-364_parentOrGuardianToPayPage.feature, cypress/e2e/functional/opal/manualAccountCreation/PO-368_employerDetails_parentAndGuardian.feature, cypress/e2e/functional/opal/manualAccountCreation/adultOrYouthOnly/PO-358_contactDetails.feature, cypress/e2e/functional/opal/manualAccountCreation/adultOrYouthOnly/PO-360_personalDetails.feature, cypress/support/projectConfig/contact_details_page.ts, cypress/support/projectConfig/personal_details_page.ts, cypress/support/step_definitions/genericSteps/geneticSteps.ts, cypress/support/step_definitions/manualAccountCreation/aliases.ts, cypress/support/step_definitions/manualAccountCreation/manualAccountCreation.ts
=> New branch for PO-360 automation tests

server/session/session-storage.ts
=> chore: update sameSite attribute in session storage configuration

server/session/session-storage.ts
Reverts hmcts/opal-frontend#639
=> Revert "chore: update sameSite attribute in session storage configuration"

charts/opal-frontend/Chart.yaml, charts/opal-frontend/values.stg.template.yaml, charts/opal-frontend/values.yaml, config/custom-environment-variables.json, config/default.json, server/csrf-token/csrf-token.ts, server/session/session-storage.ts
=> chore: update session and CSRF sameSite attribute to 'lax'

cypress.config.ts, cypress/support/step_definitions/accessibility/accessibility.ts, cypress/support/step_definitions/accountDetails/accountDetailsPage.ts, cypress/support/step_definitions/accountDetails/businessUnitAndDefendantType.ts, cypress/support/step_definitions/genericSteps/genericSteps.ts, cypress/support/step_definitions/manualAccountCreation/aliases.ts, cypress/support/step_definitions/manualAccountCreation/manualAccountCreation.ts, cypress/support/step_definitions/modeSwitch/modeSwitch.ts, cypress/support/step_definitions/signInPage/signInTest.ts, cypress/support/step_definitions/signInPage/signOutTest.ts, package.json, tsconfig.json, yarn.lock
=> migrating to cypress esbuild preprocessor

cypress/e2e/functional/opal/manualAccountCreation/adultOrYouthOnly/PO-360_personalDetails.feature, cypress/e2e/functional/opal/manualAccountCreation/adultOrYouthOnly/PO-433_addContactDetailsButton.feature, cypress/e2e/functional/opal/manualAccountCreation/adultOrYouthWithParentOrGuardian/PO-369_personalDetailsParentOrGuardian.feature
=> reducing test time

angular.json, src/app/flows/fines/fines-mac/components/fines-mac-address-block/fines-mac-address-block.component.html, src/app/flows/fines/fines-mac/components/fines-mac-address-block/fines-mac-address-block.component.spec.ts, src/app/flows/fines/fines-mac/components/fines-mac-address-block/fines-mac-address-block.component.ts, src/app/flows/fines/fines-mac/components/fines-mac-date-of-birth/fines-mac-date-of-birth.component.html, src/app/flows/fines/fines-mac/components/fines-mac-date-of-birth/fines-mac-date-of-birth.component.spec.ts, src/app/flows/fines/fines-mac/components/fines-mac-date-of-birth/fines-mac-date-of-birth.component.ts, src/app/flows/fines/fines-mac/components/fines-mac-national-insurance-number/fines-mac-national-insurance-number.component.html, src/app/flows/fines/fines-mac/components/fines-mac-national-insurance-number/fines-mac-national-insurance-number.component.spec.ts, src/app/flows/fines/fines-mac/components/fines-mac-national-insurance-number/fines-mac-national-insurance-number.component.ts, src/app/flows/fines/fines-mac/fines-mac-company-details/fines-mac-company-details-form/fines-mac-company-details-form.component.html, src/app/flows/fines/fines-mac/fines-mac-parent-guardian-details/fines-mac-parent-guardian-details-form/fines-mac-parent-guardian-details-form.component.html, src/app/flows/fines/fines-mac/fines-mac-personal-details/fines-mac-personal-details-form/fines-mac-personal-details-form.component.html
=> Potential dupe fixes

cypress/e2e/smoke/opal/accessibility/manualAccountCreation/manualAccountCreation_accessibility.feature, cypress/support/step_definitions/accessibility/accessibility.ts
The code changes include adding a new feature file and step definitions for testing the accessibility of manual account creation in the OPAL Frontend. The feature file includes scenarios for checking accessibility on different pages and signing out. The step definitions include functions for checking accessibility and navigating to URLs.
https://tools.hmcts.net/jira/browse/PO-617
https://tools.hmcts.net/jira/browse/PO-619
https://tools.hmcts.net/jira/browse/PO-621
https://tools.hmcts.net/jira/browse/PO-622
https://tools.hmcts.net/jira/browse/PO-626
https://tools.hmcts.net/jira/browse/PO-627
https://tools.hmcts.net/jira/browse/PO-636
https://tools.hmcts.net/jira/browse/PO-624
https://tools.hmcts.net/jira/browse/PO-625
=> feat: Add accessibility tests for manual account creation

charts/opal-frontend/values.stg.template.yaml
=> chore: Update OPAL_FINES_SERVICE_API_URL in values.stg.template.yaml

charts/opal-frontend/values.stg.template.yaml
=> chore: Disable SSO feature in values.stg.template.yaml

cypress/support/step_definitions/signInPage/signInTest.ts
=> chore: Update sign-in page to include 'staging' in href check

cypress/support/step_definitions/signInPage/signInTest.ts
=> Disable sso route in tests

cypress/support/step_definitions/signInPage/signInTest.ts
Reverts hmcts/opal-frontend#763
=> Revert "Disable sso route in tests"

charts/opal-frontend/values.stg.template.yaml, cypress/support/step_definitions/signInPage/signInTest.ts
=> Sso rollback

.github/renovate.json
=> chore: update renovate.json schedule for better maintenance window

cypress/e2e/functional/opal/manualAccountCreation/welshLanguages/PO-464_languagePreferencesScreen.feature, cypress/e2e/functional/opal/manualAccountCreation/welshLanguages/PO-465_languagePreferencesOnAccountDetails.feature
=> chore: update language preferences feature files

cypress/e2e/functional/opal/manualAccountCreation/welshLanguages/PO-464_languagePreferencesScreen.feature, cypress/e2e/functional/opal/manualAccountCreation/welshLanguages/PO-465_languagePreferencesOnAccountDetails.feature
Reverts hmcts/opal-frontend#813
=> Revert "chore: update language preferences feature files"

.github/renovate.json
Reverts hmcts/opal-frontend#811
=> Revert "chore: update renovate.json schedule for better maintenance window"

package.json, yarn.lock
- Remove micromatch resolution from the package.json
- Ran the npm audit and the micromatch didn't appear
- Ran the build:serve:ssr command - successful
- Ran the dev:ssr command - successful
=> micromatch resolution removed

cypress/e2e/smoke/opal/PO-224_accessibilityTests.feature
=> feat: Add "Sign in" to page body header in accessibility tests

cypress/e2e/smoke/opal/PO-224_accessibilityTests.feature
=> Adjusting failing smoke test for SSO component

src/app/services/date-service/date.service.spec.ts
- Refactor the date service unit test
- The previous approach caused test failures due to small millisecond discrepancies, even though the method was functioning correctly.
- By adjusting the precision to minutes, we ensure that the test remains robust while still verifying the correctness of the getDateNow() method.
- Example of test failure: [Build Pipeline](https://sds-build.hmcts.net/job/HMCTS/job/opal-frontend/job/PR-858/1/pipeline-console/?selected-node=106)
=> Refactor the unit test

cypress/e2e/functional/opal/paymentTerms/PO-588_AY-PGDaysInDefault.feature, cypress/support/step_definitions/signInPage/signInTest.ts
fix(tests): update feature description and increase timeout for sign-in steps
=> small test fixes

.github/renovate.json
=> chore: Remove schedule from renovate.json

src/app/components/govuk/govuk-button/readme.md
=> feat: Add GOV.UK Button Component readme

src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-remove-imposition/fines-mac-offence-details-remove-imposition.component.spec.ts, src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-remove-imposition/fines-mac-offence-details-remove-imposition.component.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/fines-mac-payload.service.ts, src/app/services/transformation-service/transformation.service.ts
N/A
Code smells addressed from here: https://sonarcloud.io/project/issues?issueStatuses=OPEN,CONFIRMED&id=opal-frontend
- Unit tests added for coverage
- Tested locally and working as expected
=> Code Smells (5 SC Issues)

package.json, src/app/services/sort-service/interfaces/sort-service-interface.ts, src/app/services/sort-service/sort-service.spec.ts, src/app/services/sort-service/sort-service.ts, yarn.lock
See [https://tools.hmcts.net/jira/browse/PO-986](https://tools.hmcts.net/jira/browse/PO-986)
-Installed Fast Sort libary
-Created Sort Service
-Created Ascending and Descending methods for Objects and arrays
-Created Unit test for the service
-Tested locally
=> PO-986 # Created the sort service and created arrays and object sorting methods.

src/app/flows/fines/fines-mac/fines-mac-offence-details/constants/fines-mac-offence-details-imposition-field-names.constant.ts, src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence-form/fines-mac-offence-details-add-an-offence-form.component.spec.ts, src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence-form/fines-mac-offence-details-add-an-offence-form.component.ts
N/A
- Update the constant name 'major_creditor' to 'major_creditor_id' in the 'fines-mac-offence-details-imposition-field-names.constant.ts' file.
- Modify the 'resultCodeListener' method in the 'fines-mac-offence-details-add-an-offence-form.component.ts' file to reset the 'creditorControl' and remove minor creditor data from the draft state and state.
- Set the value of 'needsCreditorControl' to true when the 'resultIdControl' value is 'costs' or 'compensation' in the 'resultCodeListener' method.
- Set the value of 'needsCreditorControl' to false and remove form array form group control validators when the 'resultIdControl' value is not 'costs' or 'compensation' in the 'resultCodeListener' method.
- Set the value of 'balanceRemainingControl' to the difference between 'amountImposed' and …
=> Unit Test Failing

src/app/flows/fines/fines-mac/services/fines-mac-payload/fines-mac-payload.service.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-build-account/fines-mac-payload-build-account-base.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-build-account/fines-mac-payload-build-account-defendant-company.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-build-account/fines-mac-payload-build-account-defendant-individual.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-build-account/fines-mac-payload-build-account-defendant-parent-guardian.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-build-account/fines-mac-payload-build-account-defendant.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-build-account/fines-mac-payload-build-account-offences.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-build-account/fines-mac-payload-build-account-payment-terms.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-account-notes.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-base.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-company.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-individual.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-parent-guardian.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-offences.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-payment-terms.utils.spec.ts
=> Po 1074 test optmisation

src/app/components/alphagov/alphagov-accessible-autocomplete/alphagov-accessible-autocomplete.component.spec.ts
=> Alphagov test optimisation

src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-company.utils.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-individual.utils.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-parent-guardian.utils.ts
=> Refactor payload mapping to remove unnecessary null checks

src/app/flows/fines/fines-mac/services/fines-mac-payload/fines-mac-payload.service.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-company.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-company.utils.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-individual.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-individual.utils.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-parent-guardian.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-defendant-parent-guardian.utils.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-offences.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-account-offences.utils.ts
Removed unnecessary checks, improved unit test coverage.
=> Payload unit tests 2

src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-add-alias.ts, src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-address-line-one.ts, src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-address-line-two.ts, src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-aliases.ts, src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-dob.ts, src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-forenames.ts, src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-national-insurance-number.ts, src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-postcode.ts, src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-surname.ts, src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-vehicle-make.ts, src/app/flows/fines/fines-mac/constants/controls/fines-mac-controls-vehicle-registration-mark.ts, src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence-form/mocks/fines-mac-offence-details-add-an-offence-form-minor-creditor.mocks.ts, src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-minor-creditor/constants/fines-mac-offence-details-minor-creditor-form.constant.ts
- Sonar reporting these files as 0% code coverage when they are no longer used. 
- Deleting files for cleanup
- Unit tests running as expected
- Builds correctly
=> Delete unused files to prevent 0% coverage being reported

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PO-1172
Downgrade applicationinsights
Ran through application, checked application insights on azure for data.
=> fix(deps): downgrade applicationinsights to version ~2.9.6

package.json, yarn.lock
Reverts hmcts/opal-frontend#1190
=> Revert "fix(deps): update dependency applicationinsights to v3"

src/app/components/moj/moj-header/moj-header-navigation-item/moj-header-navigation-item.component.html
- Fix the Sign in/Sign out links by added a href and removing the role
- Ran locally working as expected
- Smoke test passing locally
- Unit tests executing successfully
=> Fix Sign in/Sign out links

src/app/flows/fines/fines-mac/fines-mac-offence-details/fines-mac-offence-details-add-an-offence/fines-mac-offence-details-add-an-offence-form/fines-mac-offence-details-add-an-offence-form.component.ts
- Fixes: https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN,CONFIRMED&id=opal-frontend&open=AZUYVJB-sEbuwg6S7m8X
- Unit test & linting running as expected
=> Fix Sonar Issue

charts/opal-frontend/Chart.yaml, charts/opal-frontend/values.stg.template.yaml, charts/opal-frontend/values.yaml, config/custom-environment-variables.json, config/default.json, server/session/session-storage.ts
[PO-1284](https://tools.hmcts.net/jira/browse/PO-1284)
- Change cookie to have sameSite set to 'none'
- Change cookie to have a domain set to '.hmcts.net'
N/A
=> Cookie Change Test

charts/opal-frontend/values.stg.template.yaml, cypress/support/step_definitions/signInPage/signInTest.ts
Reverts hmcts/opal-frontend#1272
=> Revert "Switch off sso on staging"

server/modules/helmet/index.ts
- N/A
- Include application insights domain in the helmet configuration file 
- N/A
=> Include Application Insights Domain in Helmet

server/modules/helmet/index.ts
- N/A
- Adding "*.applicationinsights.azure.com" didn't work so changing to "*.azure.com" instead 
- N/A
=> Change helmet domain to look for

cypress.config.ts
=> fix(cypress): update excludeSpecPattern to omit specific test directories

Jenkinsfile_nightly
=> fix: update project name in Jenkinsfile_nightly for artifact operations

server-setup.ts
=> Use the correct value from config for the cloudRoleName for Application Insights

cypress/e2e/functional/opal/manualAccountCreation/populateAndSubmit/pages/CourtDetails.feature
=> fix: update enforcement court name in CourtDetails.feature

src/app/flows/fines/fines-draft/constants/fines-draft-tab-statuses.constant.ts, src/app/flows/fines/fines-draft/fines-draft-check-and-manage/fines-draft-check-and-manage-tabs/fines-draft-check-and-manage-tabs.component.ts, src/app/flows/fines/services/opal-fines-service/constants/opal-fines-draft-account-statues.constant.ts, src/app/flows/fines/services/opal-fines-service/enums/opal-fines-draft-account-statuses.enum.ts, src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-draft-account-statuses.interface.ts, yarn.lock
- N/A
- Change Opal Fines Draft Account Statues enum to interface/constant
- N/A
- N/A
=> Change the Draft Accounts Status from enum to constant

cypress/component/manualAccountCreation/FinesMacOffenceDetails/SearchOffenceResults/constants/search_offence_results_elements_mock.ts, cypress/component/manualAccountCreation/FinesMacOffenceDetails/SearchOffenceResults/mocks/offence_search_results_mock.ts, cypress/component/manualAccountCreation/FinesMacOffenceDetails/SearchOffenceResults/searchOffenceResults.cy.ts, cypress/e2e/functional/opal/manualAccountCreation/populateAndSubmit/pages/OffenceDetails.feature, cypress/support/step_definitions/genericSteps/inputFieldSteps.ts, cypress/support/step_definitions/searchOffences/searchOffencesSteps.ts
See [PROJ-PO-987](https://tools.hmcts.net/jira/browse/PROJ-PO987)
Adding tests for coverage of PO-987. 
Found issues have been resolved and evidence recorded on ticket.
=> Testing po 987

cypress/component/manualAccountCreation/FinesDraft/FinesDraftCheckAndValidate/FinesDraftCheckAndValidate/CheckAndValidateRejected.cy.ts, cypress/component/manualAccountCreation/FinesDraft/FinesDraftCheckAndValidate/FinesDraftCheckAndValidate/CheckAndValidateToReview.cy.ts
=> automation tests for PO-600

src/app/flows/fines/fines-mac/constants/fines-mac-business-unit-state.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/fines-mac-payload.service.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/mocks/fines-mac-payload-fines-mac-state.mock.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-business-unit.utils.spec.ts, src/app/flows/fines/fines-mac/services/fines-mac-payload/utils/fines-mac-payload-map-account/fines-mac-payload-map-business-unit.utils.ts, src/app/flows/fines/services/opal-fines-service/interfaces/opal-fines-business-unit-ref-data.interface.ts, src/app/flows/fines/services/opal-fines-service/mocks/opal-fines-business-unit-ref-data.mock.ts, src/app/flows/fines/services/opal-fines-service/opal-fines.service.ts, yarn.lock
[PO-1868](https://tools.hmcts.net/jira/browse/PO-1868)
- BE updated configurationItems to configuration_items
- Updated our interfaces, mocks, and other files accordingly 
- Tested locally and working as expected
=> Update configurationItems to configuration_items

package.json, src/app/flows/fines/fines-mac/services/fines-mac-payload/constants/fines-mac-transform-items-config.constant.ts, yarn.lock
See [PO-1796](https://tools.hmcts.net/jira/browse/PO-1796)
- Changing the structure of the payload transformation configuration objects to align with changes in the ui lib.
- Ensured payload transformation working as expected.
=> PO-1796: Align payload transformation object structure to ui lib

.github/copilot-instructions.md, README.md
=> docs: add copilot instructions for Angular development best practices

Jenkinsfile_CNP, charts/opal-frontend/values.dev.template.yaml
=> Made opal fines service defaulted to enabled
